{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":122770107,"authorName":"usenechal","from":"&quot;usenechal&quot; &lt;senechal@...-dresden.de&gt;","profile":"usenechal","replyTo":"LIST","senderId":"LDJmcRpbUjO7r2xkJStaqpoReUsdx4-g9zGW-Uoju8F9dbwSEWNA6fccyimKS33zUnp35d0cILxTe7aX-Xz2vx3MmJp5wetE1JQLNC9P3UpSkg","spamInfo":{"isSpam":false,"reason":"6"},"subject":"problem with ctml_writer on Mac OS X","postDate":"1168276303","msgId":1461,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PGVudHUwZis0MnB0QGVHcm91cHMuY29tPg=="},"prevInTopic":0,"nextInTopic":0,"prevInTime":1460,"nextInTime":1462,"topicId":1461,"numMessagesInTopic":1,"msgSnippet":"Hi, I just installed cantera-1.7.0 an my Mac (Intel-based, 10.4.8) and it works nearly perfect ;) but it seems that the automatic conversion from cti-files to","rawEmail":"Return-Path: &lt;senechal@...-dresden.de&gt;\r\nX-Sender: senechal@...-dresden.de\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 51205 invoked from network); 8 Jan 2007 17:12:51 -0000\r\nReceived: from unknown (66.218.66.172)\n  by m33.grp.scd.yahoo.com with QMQP; 8 Jan 2007 17:12:51 -0000\r\nReceived: from unknown (HELO n7c.bullet.sp1.yahoo.com) (69.147.64.167)\n  by mta4.grp.scd.yahoo.com with SMTP; 8 Jan 2007 17:12:51 -0000\r\nReceived: from [216.252.122.219] by n7.bullet.sp1.yahoo.com with NNFMP; 08 Jan 2007 17:11:43 -0000\r\nReceived: from [209.73.164.83] by t4.bullet.sp1.yahoo.com with NNFMP; 08 Jan 2007 17:11:43 -0000\r\nReceived: from [66.218.66.90] by t7.bullet.scd.yahoo.com with NNFMP; 08 Jan 2007 17:11:43 -0000\r\nDate: Mon, 08 Jan 2007 17:11:43 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;entu0f+42pt@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=&quot;ISO-8859-1&quot;\r\nContent-Transfer-Encoding: quoted-printable\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-compose\r\nX-eGroups-Msg-Info: 1:6:0:0\r\nFrom: &quot;usenechal&quot; &lt;senechal@...-dresden.de&gt;\r\nSubject: problem with ctml_writer on Mac OS X\r\nX-Yahoo-Group-Post: member; u=122770107; y=eQTO7T15DdvkFvN-pRGMju8N3Y-Mf_6rev80sjOXuWIjqnwI\r\nX-Yahoo-Profile: usenechal\r\n\r\nHi,\n\nI just installed cantera-1.7.0 an my Mac (Intel-based, 10.4.8) and it\n=\r\nworks nearly perfect ;) but it seems that the automatic conversion\nfrom cti=\r\n-files to xml is not working in python(2.5). When I open\npython and type \nf=\r\nrom Cantera import *\ngri=3DIdealGasMix(&#39;gri.cti&#39;)\n\neverything works. But th=\r\ne same in Idle there is the error:\n\nTraceback (most recent call last):\n  Fi=\r\nle &quot;./.cttmp1168275415.pyw&quot;, line 1, in ?\n    from ctml_writer import *\nImp=\r\nortError: No module named ctml_writer\n\n\nTraceback (most recent call last):\n=\r\n  File &quot;/Users/usenechal/Work/kleiner Beleg/modified\nGRI30/heizwert.py&quot;, li=\r\nne 15, in &lt;module&gt;\n    gri3 =3D IdealGasMix(&#39;gri30.cti&#39;)\n  File\n&quot;/Library/F=\r\nrameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/Cantera=\r\n/gases.py&quot;,\nline 22, in IdealGasMix\n    return Solution(src=3Dsrc,id=3Did,l=\r\noglevel=3Dloglevel)\n  File\n&quot;/Library/Frameworks/Python.framework/Versions/2=\r\n.5/lib/python2.5/site-packages/Cantera/solution.py&quot;,\nline 49, in __init__\n =\r\n   ThermoPhase.__init__(self, xml_phase=3Ds)\n  File\n&quot;/Library/Frameworks/Py=\r\nthon.framework/Versions/2.5/lib/python2.5/site-packages/Cantera/ThermoPhase=\r\n.py&quot;,\nline 55, in __init__\n    self._phase_id =3D _cantera.ThermoFromXML(xm=\r\nl_phase._xml_id)\nerror: \n\n************************************************\n=\r\n                Cantera Error!                  \n**************************=\r\n**********************\n\n\nProcedure: importPhase\nError:   no data for specie=\r\ns \n\n\nIs there a conflict with the preinstalled internal python(2.3) on\nMac-=\r\nOS? I also tried the python-examples, but it&#39;s the same...\nI also applied t=\r\nhe suggested fix found on this newsgroup (from\n14.09.2005 or so).\n\nbest reg=\r\nards\nulf\n\n\n"}}