{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":118898663,"authorName":"erikboschek","from":"&quot;erikboschek&quot; &lt;erikboschek@...&gt;","profile":"erikboschek","replyTo":"LIST","senderId":"vU_kDHduSthLJt8cL05wykb-OqT_Ha5HzKYuRJAB_iTJcLxR9tc0L2WYDHOewH67VoCI4womYQShb6-xBsQvaDs8JZwHqg8ebW2oVg","spamInfo":{"isSpam":false,"reason":"6"},"subject":"Rntime Error!","postDate":"1169719912","msgId":1480,"canDelete":false,"contentTrasformed":false,"systemMessage":true,"headers":{"messageIdInHeader":"PGVwOXZwOCs2MGlxQGVHcm91cHMuY29tPg=="},"prevInTopic":0,"nextInTopic":1484,"prevInTime":1479,"nextInTime":1481,"topicId":1480,"numMessagesInTopic":3,"msgSnippet":"I ve run into a problem while looking at the combustor.py example for python (steady flow combustor problem with two mass flow controllers...etc.). If I run","rawEmail":"Return-Path: &lt;erikboschek@...&gt;\r\nReceived: (qmail 98187 invoked from network); 25 Jan 2007 19:54:44 -0000\r\nReceived: from unknown (66.218.66.216)\n  by m39.grp.scd.yahoo.com with QMQP; 25 Jan 2007 19:54:44 -0000\r\nReceived: from unknown (HELO n21a.bullet.scd.yahoo.com) (66.94.237.50)\n  by mta1.grp.scd.yahoo.com with SMTP; 25 Jan 2007 19:54:44 -0000\r\nReceived: from [66.218.69.4] by n21.bullet.scd.yahoo.com with NNFMP; 25 Jan 2007 19:52:39 -0000\r\nReceived: from [66.218.66.84] by t4.bullet.scd.yahoo.com with NNFMP; 25 Jan 2007 19:52:39 -0000\r\nX-Sender: erikboschek@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 32197 invoked from network); 25 Jan 2007 10:12:09 -0000\r\nReceived: from unknown (66.218.67.35)\n  by m27.grp.scd.yahoo.com with QMQP; 25 Jan 2007 10:12:09 -0000\r\nReceived: from unknown (HELO n11d.bullet.scd.yahoo.com) (66.218.67.60)\n  by mta9.grp.scd.yahoo.com with SMTP; 25 Jan 2007 10:12:09 -0000\r\nReceived: from [209.73.164.83] by n22.bullet.scd.yahoo.com with NNFMP; 25 Jan 2007 10:11:52 -0000\r\nReceived: from [66.218.66.90] by t7.bullet.scd.yahoo.com with NNFMP; 25 Jan 2007 10:11:52 -0000\r\nDate: Thu, 25 Jan 2007 10:11:52 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;ep9vp8+60iq@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=&quot;ISO-8859-1&quot;\r\nContent-Transfer-Encoding: quoted-printable\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-system\r\nX-eGroups-Msg-Info: 1:6:0:0\r\nFrom: &quot;erikboschek&quot; &lt;erikboschek@...&gt;\r\nSubject: Rntime Error!\r\nX-Yahoo-Group-Post: member; u=118898663; y=f9gxQ11S5345bogBJ9hCNTPIZbGkcudz1HAB7NdeTK2xxKXO40E\r\nX-Yahoo-Profile: erikboschek\r\nX-eGroups-Approved-By: dggoodwin &lt;dgoodwin@...&gt; via web; 25 Jan 2007 19:52:37 -0000\r\n\r\nI&#39;ve run into a problem while looking at the &quot;combustor.py&quot; example\nfor pyt=\r\nhon (steady flow combustor problem with two mass flow\ncontrollers...etc.). =\r\nIf I run this twice within the same python\nsession (or loop the solution mo=\r\nre than once) it crashes and gives a\nRuntime Error &quot;Microsoft Visual C++ Ru=\r\nntime Library&quot;...Program:\nC:Python25&#92;pythonw.exe...&quot;This application has re=\r\nquested the Runtime\nto terminate it in an unusual way&quot; \n\nHas anyone had any=\r\n experience with this problem or have a fix? or is\nit purely a windows prob=\r\nlem?\n\nUsing: Windows XP sp 2, python 2.5, cantera 1.7 (from *.msi file)\n\n\nT=\r\nhanks,\n\nErik\n\n\n"}}