{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":291427459,"authorName":"bertbell2","from":"&quot;bertbell2&quot; &lt;robert.bell@...&gt;","profile":"bertbell2","replyTo":"LIST","senderId":"IoFgNX0Eb9g9wAqWdK-6DgAYjiV8VSDGi9wfA_ajX5c4YyDbfZhnNVA7QHFbS2gUQw2zKtX1PTYGneTQQ8WE8_EKpvE_gWlCsVv0Ld2L","spamInfo":{"isSpam":false,"reason":"6"},"subject":"C++ Client, CTI conversion to XML fails","postDate":"1170285740","msgId":1499,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PGVwcjhiZCtkc2xwQGVHcm91cHMuY29tPg=="},"prevInTopic":0,"nextInTopic":1501,"prevInTime":1498,"nextInTime":1500,"topicId":1499,"numMessagesInTopic":3,"msgSnippet":"Hello: I am developing a C++ Cantera client.  I am seeing directory depth effect the ability of the python interpreter to produce the XML file from a CTI file.","rawEmail":"Return-Path: &lt;robert.bell@...&gt;\r\nX-Sender: robert.bell@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 11754 invoked from network); 31 Jan 2007 23:22:32 -0000\r\nReceived: from unknown (66.218.66.217)\n  by m47.grp.scd.yahoo.com with QMQP; 31 Jan 2007 23:22:31 -0000\r\nReceived: from unknown (HELO n13a.bullet.sp1.yahoo.com) (69.147.64.112)\n  by mta2.grp.scd.yahoo.com with SMTP; 31 Jan 2007 23:22:31 -0000\r\nReceived: from [216.252.122.216] by n13.bullet.sp1.yahoo.com with NNFMP; 31 Jan 2007 23:22:23 -0000\r\nReceived: from [66.218.69.4] by t1.bullet.sp1.yahoo.com with NNFMP; 31 Jan 2007 23:22:23 -0000\r\nReceived: from [66.218.66.88] by t4.bullet.scd.yahoo.com with NNFMP; 31 Jan 2007 23:22:23 -0000\r\nDate: Wed, 31 Jan 2007 23:22:20 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;epr8bd+dslp@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=&quot;ISO-8859-1&quot;\r\nContent-Transfer-Encoding: quoted-printable\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-compose\r\nX-eGroups-Msg-Info: 1:6:0:0\r\nFrom: &quot;bertbell2&quot; &lt;robert.bell@...&gt;\r\nSubject: C++ Client, CTI conversion to XML fails\r\nX-Yahoo-Group-Post: member; u=291427459; y=tQeZTERik8KZsQcemS2UnOW0JVnoUR9xgXQ5PrCrbvLu1DmH\r\nX-Yahoo-Profile: bertbell2\r\n\r\nHello:\n\nI am developing a C++ Cantera client.  I am seeing directory depth =\r\n\neffect the ability of the python interpreter to produce the XML file \nfrom=\r\n a CTI file.  If I run a python script in the same directory it \nworks prop=\r\nerly.\n\nIf I use \n&#39;C:&#92;Cantera&#92;demos&#92;Python&#92;equilibrium&#39; my code runs\nusing\n&#39;=\r\nC:&#92;Cantera&#92;demos&#92;Python&#92;equilibrium&#92;testdir_1&#39; it fails with the \nfollowing=\r\n Cantera error and traceback info.\n\nTraceback (most recent call last):\n  Fi=\r\nle &quot;C:&#92;DOCUME~1&#92;bert&#92;LOCALS~1&#92;Temp/.cttmp1170284516.pyw&quot;, line 7, \nin &lt;modu=\r\nle&gt;\n    execfile(file)\nIOError: [Errno 2] No such file or \ndirectory: &#39;C:&#92;&#92;=\r\nCantera&#92;&#92;demos&#92;&#92;Python&#92;&#92;equilibrium&#92;testdir_1\n&#92;&#92;MyMechV15.cti&#39;\n\n\n\n*********=\r\n***************************************\n                   Cantera Error!\n*=\r\n***********************************************\n\n\nProcedure: ct2ctml\nError:=\r\n     could not convert input file to CTML.\n Command line was:\nC:&#92;PYTHON25&#92;P=\r\nYTHON.EXE C:&#92;DOCUME~1&#92;bert&#92;LOCALS~1\n&#92;Temp/.cttmp1170284516.pyw&gt; ct2ctml.log=\r\n 2&gt;&1\n\nI dump the full path to the cti file and it is correct.  \n\nNote the =\r\nsingle &#39;&#92;&#39; between dir names equilibrium and testdir_1 where \nthe others ar=\r\ne &quot;&#92;&#92;&quot;.  \n\nI would like to try and fix this bug.  Is it more likely that th=\r\ne \ntrouble is in C++ or the Cantera python support code?\n\n\n\n\n"}}