{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":232686110,"authorName":"birutebunkute","from":"&quot;birutebunkute&quot; &lt;birutebunkute@...&gt;","profile":"birutebunkute","replyTo":"LIST","senderId":"YBUuCn-4yEDUEkXLg0NVfJu71L5I21GZYq-lsbRT9MUFKoBgc67ZsKovmWWgnPJAPXP2mwtJ5ZYfsMyir6k9TGwix29atezmOQ8Z9_rFi7Vssg","spamInfo":{"isSpam":false,"reason":"6"},"subject":"MixMaster launching problem","postDate":"1178141303","msgId":1616,"canDelete":false,"contentTrasformed":false,"systemMessage":true,"headers":{"messageIdInHeader":"PGYxYXZwbis2dTFkQGVHcm91cHMuY29tPg=="},"prevInTopic":0,"nextInTopic":1746,"prevInTime":1615,"nextInTime":1617,"topicId":1616,"numMessagesInTopic":3,"msgSnippet":"Dear Dr. David Goodwin, I am trying to launch MixMaster, but I couldn t succeed so far. It gives me the following error in Python Shell: Traceback (most recent","rawEmail":"Return-Path: &lt;birutebunkute@...&gt;\r\nReceived: (qmail 85545 invoked from network); 3 May 2007 05:46:40 -0000\r\nReceived: from unknown (66.218.66.70)\n  by m47.grp.scd.yahoo.com with QMQP; 3 May 2007 05:46:40 -0000\r\nReceived: from unknown (HELO n31.bullet.scd.yahoo.com) (66.94.237.25)\n  by mta12.grp.scd.yahoo.com with SMTP; 3 May 2007 05:46:40 -0000\r\nReceived: from [66.218.69.1] by n31.bullet.scd.yahoo.com with NNFMP; 03 May 2007 05:46:40 -0000\r\nReceived: from [66.218.66.77] by t1.bullet.scd.yahoo.com with NNFMP; 03 May 2007 05:46:40 -0000\r\nX-Sender: birutebunkute@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 26800 invoked from network); 2 May 2007 21:29:16 -0000\r\nReceived: from unknown (66.218.66.68)\n  by m43.grp.scd.yahoo.com with QMQP; 2 May 2007 21:29:14 -0000\r\nReceived: from unknown (HELO n19.bullet.sp1.yahoo.com) (69.147.64.216)\n  by mta11.grp.scd.yahoo.com with SMTP; 2 May 2007 21:29:12 -0000\r\nReceived: from [216.252.122.216] by n19.bullet.sp1.yahoo.com with NNFMP; 02 May 2007 21:28:24 -0000\r\nReceived: from [66.218.69.5] by t1.bullet.sp1.yahoo.com with NNFMP; 02 May 2007 21:28:24 -0000\r\nReceived: from [66.218.66.77] by t5.bullet.scd.yahoo.com with NNFMP; 02 May 2007 21:28:24 -0000\r\nDate: Wed, 02 May 2007 21:28:23 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;f1avpn+6u1d@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=&quot;ISO-8859-1&quot;\r\nContent-Transfer-Encoding: quoted-printable\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-system\r\nX-eGroups-Msg-Info: 1:6:0:0\r\nFrom: &quot;birutebunkute&quot; &lt;birutebunkute@...&gt;\r\nSubject: MixMaster launching problem\r\nX-Yahoo-Group-Post: member; u=232686110; y=xvQlfQnR-2W-QefnDfBx64z45S39IrkC3ZCE78b--uJOG5mfWqQxpA\r\nX-Yahoo-Profile: birutebunkute\r\nX-eGroups-Approved-By: dggoodwin &lt;dgoodwin@...&gt; via web; 03 May 2007 05:46:38 -0000\r\n\r\nDear Dr. David Goodwin,\n\nI am trying to launch MixMaster, but I couldn&#39;t su=\r\ncceed so far. It \ngives me the following error in Python Shell:\n\nTraceback =\r\n(most recent call last):\n  File &quot;C:&#92;Cantera&#92;mixmaster.py&quot;, line 1, in &lt;modu=\r\nle&gt;\n    from MixMaster import MixMaster\n  File &quot;C:&#92;Python25&#92;Lib&#92;site-packag=\r\nes&#92;MixMaster&#92;__init__.py&quot;, line 4, \nin &lt;module&gt;\n    from main import MixMas=\r\nter\n  File &quot;C:&#92;Python25&#92;lib&#92;site-packages&#92;MixMaster&#92;main.py&quot;, line 25, in \n=\r\n&lt;module&gt;\n    from CompositionFrame import MixtureFrame\nImportError: cannot =\r\nimport name MixtureFrame\n\nI checked the CompositionFrame.py file in C:&#92;Pyth=\r\non25&#92;lib&#92;site-\npackages&#92;MixMaster folder and it is empty.\nI would be very t=\r\nhankful if you would send me this file or at least \nthe code, which need to=\r\n be present in this file, so I could repair it.\nThank you very much for any=\r\n reply.\n\nBest regards,\nBirute\n\n\n\n"}}