{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":304378662,"authorName":"rustoleump","from":"&quot;rustoleump&quot; &lt;rustoleump@...&gt;","profile":"rustoleump","replyTo":"LIST","senderId":"zgxXqjLM2vbA2bnFLHaPrWZhc0-kMse2Z02A7WeZ2rtl9pMrln5C0cfW4YQ3MESfXrKAPj1T6Fa8bwY5BM_cQ2kc8Tx0tRL-4is","spamInfo":{"isSpam":false,"reason":"6"},"subject":"Import error: No module named Cantera","postDate":"1179342991","msgId":1637,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PGYyZmxhZisxYjAyQGVHcm91cHMuY29tPg=="},"prevInTopic":0,"nextInTopic":1638,"prevInTime":1636,"nextInTime":1638,"topicId":1637,"numMessagesInTopic":2,"msgSnippet":"I continue to receive the following error: Traceback (most recent call last): File /Applications/Cantera/demos/python/flames/adiabatic_flame.py , line 5, in ","rawEmail":"Return-Path: &lt;rustoleump@...&gt;\r\nX-Sender: rustoleump@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 12312 invoked from network); 16 May 2007 19:18:49 -0000\r\nReceived: from unknown (66.218.66.68)\n  by m49.grp.scd.yahoo.com with QMQP; 16 May 2007 19:18:49 -0000\r\nReceived: from unknown (HELO n15c.bullet.sp1.yahoo.com) (69.147.64.120)\n  by mta11.grp.scd.yahoo.com with SMTP; 16 May 2007 19:18:46 -0000\r\nReceived: from [216.252.122.219] by n15.bullet.sp1.yahoo.com with NNFMP; 16 May 2007 19:16:32 -0000\r\nReceived: from [66.218.69.4] by t4.bullet.sp1.yahoo.com with NNFMP; 16 May 2007 19:16:32 -0000\r\nReceived: from [66.218.66.79] by t4.bullet.scd.yahoo.com with NNFMP; 16 May 2007 19:16:32 -0000\r\nDate: Wed, 16 May 2007 19:16:31 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;f2flaf+1b02@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=&quot;ISO-8859-1&quot;\r\nContent-Transfer-Encoding: quoted-printable\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-compose\r\nX-eGroups-Msg-Info: 1:6:0:0\r\nFrom: &quot;rustoleump&quot; &lt;rustoleump@...&gt;\r\nSubject: Import error: No module named Cantera\r\nX-Yahoo-Group-Post: member; u=304378662; y=AnvsGZ3nw4VQoNFWJRPnepJYUV7zLp3pvKej_lgSgDn3jFNl3Q\r\nX-Yahoo-Profile: rustoleump\r\n\r\nI continue to receive the following error:\n\nTraceback (most recent call las=\r\nt):\n  File &quot;/Applications/Cantera/demos/python/flames/adiabatic_flame.py&quot;, =\r\nline 5, in \n&lt;module&gt;\n    from Cantera import *\nImportError: No module named=\r\n Cantera\n\nI had successfully installed from CVS on my Mac (iBook 10.4.9, pp=\r\nc, MacPython 2.5, \nnumarray 1.5.2, gcc, sundials) and successfully run seve=\r\nral python files (flame1.py, \nflame2.py).  I then moved on to run a modifie=\r\nd version of the adiabatic_flame.py file for \nmy particular case.  This is =\r\nwhen I first received this error.  I have executed the source \ncommand stat=\r\ned at the end of the install and verified that my PATH has what I think is =\r\n\nrequired:\n\n/Applications/Cantera/bin:/Library/Frameworks/Python.framework/=\r\nVersions/Current/\nbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/lo=\r\ncal/graphviz-2.12/bin:/\nApplications:/usr/local:/Applications/MATLAB73/bin:=\r\n/bin:/sbin:/usr/bin:/usr/sbin\n\nI also tried several files in MATLAB (flame,=\r\n flame1, ignite, and others) and all had an error \nwith gri30 and IdealGasM=\r\nix.\n\nI imagine I&#39;ve missed something somewhere along the line, but I don&#39;t =\r\nknow where.  It \nseems odd to me that it worked for several files then stop=\r\nped.  In perhaps a somewhat \nhasty response, I deleted the Cantera folder u=\r\nnder Applications and re-installed Cantera.  I \ncontinue to receive the sam=\r\ne error.  Does anyone have any ideas on how to remove this \nerror?  Thanks.=\r\n\n\nRusty\n\n\n"}}