{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":77108688,"authorName":"Richard","from":"&quot;Richard&quot; &lt;rhw27@...&gt;","profile":"r_west1e","replyTo":"LIST","senderId":"G9dhEnr0u-u--Vsq3go72jJ-jgaZUX9O5t0dKsjklyamp5D3cOiJMZWZXhz7OFiotSPMn0Uc_2TrfMvJ5KPXP0JC","spamInfo":{"isSpam":false,"reason":"6"},"subject":"Re: Problem with sundials-2.3.0/MacOSX/python? Symbol not found: _N_VNew","postDate":"1208977888","msgId":1906,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PGZ1bzFsMCtoNGV1QGVHcm91cHMuY29tPg==","inReplyToHeader":"PDlBMjk0NDM5LTJCMTUtNEQ5NC04Q0Y1LTZEMjhDMTc4RjkwRUBjYW0uYWMudWs+"},"prevInTopic":1905,"nextInTopic":0,"prevInTime":1905,"nextInTime":1907,"topicId":1905,"numMessagesInTopic":2,"msgSnippet":"I have now successfully compiled and run Cantera in Python. To do this I had to edit the preconfig file to stop it using sundials","rawEmail":"Return-Path: &lt;rhw27@...&gt;\r\nX-Sender: rhw27@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nX-Received: (qmail 77500 invoked from network); 23 Apr 2008 19:11:32 -0000\r\nX-Received: from unknown (66.218.67.94)\n  by m54.grp.scd.yahoo.com with QMQP; 23 Apr 2008 19:11:32 -0000\r\nX-Received: from unknown (HELO n51c.bullet.mail.sp1.yahoo.com) (66.163.168.185)\n  by mta15.grp.scd.yahoo.com with SMTP; 23 Apr 2008 19:11:32 -0000\r\nX-Received: from [216.252.122.218] by n51.bullet.mail.sp1.yahoo.com with NNFMP; 23 Apr 2008 19:11:29 -0000\r\nX-Received: from [209.73.164.86] by t3.bullet.sp1.yahoo.com with NNFMP; 23 Apr 2008 19:11:29 -0000\r\nX-Received: from [66.218.66.90] by t8.bullet.scd.yahoo.com with NNFMP; 23 Apr 2008 19:11:29 -0000\r\nDate: Wed, 23 Apr 2008 19:11:28 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;fuo1l0+h4eu@...&gt;\r\nIn-Reply-To: &lt;9A294439-2B15-4D94-8CF5-6D28C178F90E@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=&quot;ISO-8859-1&quot;\r\nContent-Transfer-Encoding: quoted-printable\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-compose\r\nX-eGroups-Msg-Info: 1:6:0:0:0\r\nFrom: &quot;Richard&quot; &lt;rhw27@...&gt;\r\nSubject: Re: Problem with sundials-2.3.0/MacOSX/python? Symbol not found: _N_VNew\r\nX-Yahoo-Group-Post: member; u=77108688; y=DiOOE4OAOu72prXadCjyE1sh05CiIVD7CR4-Co8CnYF3e5M\r\nX-Yahoo-Profile: r_west1e\r\n\r\nI have now successfully compiled and run Cantera in Python. To do this I ha=\r\nd to edit the \npreconfig file to stop it using sundials (USE_SUNDIALS=3D${U=\r\nSE_SUNDIALS:=3D&#39;n&#39;}).\n\nIt would be nice to have sensitivity analysis, so if=\r\n anyone can help me build Cantera with \nSundials I&#39;d be very grateful. \n\nRi=\r\nchard\n\n\n--- In cantera@yahoogroups.com, Richard West &lt;rhw27@...&gt; wrote:\n&gt;\n&gt;=\r\n Dear all,\n&gt; I have spent all day trying to get Cantera up and running on m=\r\ny Mac  \n&gt; (Mac OS version 10.4.11) and have not yet succeeded.\n&gt; \n&gt; I check=\r\ned out Cantera from CVS, installed the latest version sundials  \n&gt; (2.3.0),=\r\n and built and installed everything.\n&gt; In python, the simple command &quot;Impor=\r\nt Cantera&quot; causes the following  \n&gt; error:\n&gt; \n&gt; \n&gt;    File &quot;/Library/Framew=\r\norks/Python.framework/Versions/2.5/lib/ \n&gt; python2.5/site-packages/Cantera/=\r\n__init__.py&quot;, line 7, in &lt;module&gt;\n&gt;      import _cantera\n&gt; ImportError: dlo=\r\npen(/Library/Frameworks/Python.framework/Versions/2.5/ \n&gt; lib/python2.5/sit=\r\ne-packages/Cantera/_cantera.so, 2): Symbol not  \n&gt; found: _N_VNew\n&gt;    Refe=\r\nrenced from: /Library/Frameworks/Python.framework/Versions/2.5/ \n&gt; lib/pyth=\r\non2.5/site-packages/Cantera/_cantera.so\n&gt;    Expected in: dynamic lookup\n&gt; =\r\n\n&gt; I have tried rebuilding, reconfiguring, and redoing everything many  \n&gt; =\r\ntimes in many orders.\n&gt; I have tried reconfiguring sundials with --enable-s=\r\nhared to allow  \n&gt; dynamic shared libraries, in case that was the issue, bu=\r\nt it still  \n&gt; doesn&#39;t work.\n&gt; \n&gt; Does anyone have any ideas?\n&gt; \n&gt; Many tha=\r\nnks,\n&gt; \n&gt; Richard\n&gt;\n\n\n\n\n"}}