{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":184860759,"authorName":"kvirgilm","from":"&quot;kvirgilm&quot; &lt;kvm@...&gt;","profile":"kvirgilm","replyTo":"LIST","senderId":"IMdZpAzwE7lN4Rqewj4CyG5D8D_YG6DnCddFYXUkiRkj0T4L9NJiq9_y0ZQjsjPdWHSMFZ2uK3-Wu0QxXkZFAwQ","spamInfo":{"isSpam":false,"reason":"0"},"subject":"Examples won&#39;t work for python","postDate":"1087497536","msgId":424,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PGNhc29nMCt1amxmQGVHcm91cHMuY29tPg=="},"prevInTopic":0,"nextInTopic":425,"prevInTime":423,"nextInTime":425,"topicId":424,"numMessagesInTopic":4,"msgSnippet":"I checked out the code with cvs, ran make and install. Now the python examples won t work.  I get the following error. python mix1.py Traceback (most recent","rawEmail":"Return-Path: &lt;kvm@...&gt;\r\nX-Sender: kvm@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 71792 invoked from network); 17 Jun 2004 18:39:25 -0000\r\nReceived: from unknown (66.218.66.218)\n  by m25.grp.scd.yahoo.com with QMQP; 17 Jun 2004 18:39:25 -0000\r\nReceived: from unknown (HELO n2.grp.scd.yahoo.com) (66.218.66.75)\n  by mta3.grp.scd.yahoo.com with SMTP; 17 Jun 2004 18:39:25 -0000\r\nReceived: from [66.218.67.157] by n2.grp.scd.yahoo.com with NNFMP; 17 Jun 2004 18:38:56 -0000\r\nDate: Thu, 17 Jun 2004 18:38:56 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;casog0+ujlf@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=ISO-8859-1\r\nContent-Length: 575\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-eGroups-Remote-IP: 66.218.66.75\r\nFrom: &quot;kvirgilm&quot; &lt;kvm@...&gt;\r\nSubject: Examples won&#39;t work for python\r\nX-Yahoo-Group-Post: member; u=184860759\r\nX-Yahoo-Profile: kvirgilm\r\n\r\nI checked out the code with cvs, ran make and install. \n \nNow the python examples won&#39;t work.  I get the following error. \n \npython mix1.py \nTraceback (most recent call last): \n  File &quot;mix1.py&quot;, line 18, in ? \n    from Cantera import * \n  File &quot;/usr/lib/python2.2/site-packages/Cantera/__init__.py&quot;, line 9, in ? \n    from exceptions import * \n  File &quot;/usr/lib/python2.2/site-packages/Cantera/exceptions.py&quot;, line 5, in ? \n    import _cantera \nImportError: /usr/lib/python2.2/site-packages/Cantera/_cantera.so: \nundefined symbol: _ZTVN7Cantera9PureFluidE \n \nThanks, \n \nKarl \n\n\n"}}