{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":179976060,"authorName":"freehdom","from":"&quot;freehdom&quot; &lt;jef15@...&gt;","profile":"freehdom","replyTo":"LIST","senderId":"yHzykgL3ZIy1xHZkxMM02NJsPym0FiGl111dGVY0lCr-23tEVbh9x1YY5Ib6txyrokMXp9SD1PcjAuRc1PuOxoGpUcFc","spamInfo":{"isSpam":false,"reason":"0"},"subject":"Mac OS X permissions issues","postDate":"1100972317","msgId":595,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PGNubnZldCs4cmx2QGVHcm91cHMuY29tPg=="},"prevInTopic":0,"nextInTopic":597,"prevInTime":594,"nextInTime":596,"topicId":595,"numMessagesInTopic":2,"msgSnippet":"Hi all - I m having some trouble with Cantera on OS X 10.3.6. When running the python demos, I get the following error: ","rawEmail":"Return-Path: &lt;jef15@...&gt;\r\nX-Sender: jef15@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 90712 invoked from network); 20 Nov 2004 17:39:33 -0000\r\nReceived: from unknown (66.218.66.218)\n  by m22.grp.scd.yahoo.com with QMQP; 20 Nov 2004 17:39:33 -0000\r\nReceived: from unknown (HELO n21a.bulk.scd.yahoo.com) (66.94.237.50)\n  by mta3.grp.scd.yahoo.com with SMTP; 20 Nov 2004 17:39:33 -0000\r\nReceived: from [66.218.69.1] by n21.bulk.scd.yahoo.com with NNFMP; 20 Nov 2004 17:39:08 -0000\r\nReceived: from [66.218.67.144] by mailer1.bulk.scd.yahoo.com with NNFMP; 20 Nov 2004 17:39:08 -0000\r\nDate: Sat, 20 Nov 2004 17:38:37 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;cnnvet+8rlv@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=ISO-8859-1\r\nContent-Length: 1977\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-compose\r\nX-eGroups-Remote-IP: 66.94.237.50\r\nFrom: &quot;freehdom&quot; &lt;jef15@...&gt;\r\nSubject: Mac OS X permissions issues\r\nX-Yahoo-Group-Post: member; u=179976060\r\nX-Yahoo-Profile: freehdom\r\n\r\n\nHi all -\n\nI&#39;m having some trouble with Cantera on OS X 10.3.6. When running the python demos, I \nget the following error:\n____________________________________________________________________\n[/Applications/Cantera/demos/python] user% python flame1.py \nTraceback (most recent call last):\n  File &quot;flame1.py&quot;, line 44, in ?\n    gas = IdealGasMix(rxnmech, mix)\n  File &quot;/System/Library/Frameworks/Python.framework/Versions/2.3/lib/python2.3/site-\npackages/Cantera/gases.py&quot;, line 22, in IdealGasMix\n    return Solution(src=src,id=id,loglevel=loglevel)\n  File &quot;/System/Library/Frameworks/Python.framework/Versions/2.3/lib/python2.3/site-\npackages/Cantera/solution.py&quot;, line 38, in __init__\n    root = XML.XML_Node(name = &#39;doc&#39;, src = src, preprocess = 1)\n  File &quot;/System/Library/Frameworks/Python.framework/Versions/2.3/lib/python2.3/site-\npackages/Cantera/XML.py&quot;, line 35, in __init__\n    self._xml_id = _cantera.xml_get_XML_File(src)\ncantera.error: \n\n************************************************\n                Cantera Error!                  \n************************************************\n\n\nProcedure: ct2ctml\nError:   cannot open ./.cttmp1100971050.pyw for writing.\n______________________________________________________________\n\nThis error is resolved when I type:\n[/Applications/Cantera/demos/python] user% sudo python flame1.py \n\nWhile this is fine for Cantera in python in a terminal, I get the same error in Matlab and in \nPython IDE.\n\nI think the main issue is the directory location for Cantera. When using the OSX installer \nfrom sourceforge, I don&#39;t think it uses the writeable /usr/local location, whereas an install \nfrom the source code does. Is the source code install the currently\nbetter approach for OS X? Or should I just change a few permissions and environment \nvariables to fix the current problem?\n\nI think I have the right Python, MacPython, and Numpy parts installed (though that has \nbeen challenging too).\n\nThanks for any help here!\n\nJosh Freeh\n\n\n\n\n"}}