{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":236082574,"authorName":"cassandralguy","from":"&quot;cassandralguy&quot; &lt;jcdoll@...&gt;","profile":"cassandralguy","replyTo":"LIST","senderId":"4niyqiQzJ-ZPGvO8uzR4kIYClt3AACa4X6MWz2ckqhcx4Y4Yi5xlWS44SDMZHecjxKiBN5cIzKxfGuvow7tF6_KgUiCZIZLIyQ","spamInfo":{"isSpam":false,"reason":"12"},"subject":"Re: 1.6.0 on Mac OS X 10.4","postDate":"1126675515","msgId":989,"canDelete":false,"contentTrasformed":false,"systemMessage":true,"headers":{"messageIdInHeader":"PGRnOGM3cisxZ3QxQGVHcm91cHMuY29tPg==","inReplyToHeader":"PDk0NTY2NGY1MDUwOTAzMjIwNzNjN2E5ZWM2QG1haWwuZ21haWwuY29tPg=="},"prevInTopic":973,"nextInTopic":990,"prevInTime":988,"nextInTime":990,"topicId":973,"numMessagesInTopic":3,"msgSnippet":"I fixed the problem. In python I ran the following commands: import sys print sys.path which indicated that /Applications/Cantera/bin and /Library/Python/2.3/","rawEmail":"Return-Path: &lt;jcdoll@...&gt;\r\nReceived: (qmail 11999 invoked from network); 15 Sep 2005 16:44:14 -0000\r\nReceived: from unknown (66.218.66.217)\n  by m15.grp.scd.yahoo.com with QMQP; 15 Sep 2005 16:44:14 -0000\r\nReceived: from unknown (HELO n21a.bulk.scd.yahoo.com) (66.94.237.50)\n  by mta2.grp.scd.yahoo.com with SMTP; 15 Sep 2005 16:44:13 -0000\r\nComment: DomainKeys? See http://antispam.yahoo.com/domainkeys\r\nReceived: from [66.218.69.3] by n21.bulk.scd.yahoo.com with NNFMP; 15 Sep 2005 16:43:54 -0000\r\nReceived: from [66.218.66.74] by mailer3.bulk.scd.yahoo.com with NNFMP; 15 Sep 2005 16:43:54 -0000\r\nX-Sender: jcdoll@...\r\nX-Apparently-To: cantera@yahoogroups.com\r\nReceived: (qmail 55408 invoked from network); 14 Sep 2005 05:25:19 -0000\r\nReceived: from unknown (66.218.66.166)\n  by m25.grp.scd.yahoo.com with QMQP; 14 Sep 2005 05:25:19 -0000\r\nReceived: from unknown (HELO n7a.bulk.scd.yahoo.com) (66.94.237.41)\n  by mta5.grp.scd.yahoo.com with SMTP; 14 Sep 2005 05:25:19 -0000\r\nComment: DomainKeys? See http://antispam.yahoo.com/domainkeys\r\nReceived: from [66.218.69.2] by n7.bulk.scd.yahoo.com with NNFMP; 14 Sep 2005 05:25:16 -0000\r\nReceived: from [66.218.66.88] by mailer2.bulk.scd.yahoo.com with NNFMP; 14 Sep 2005 05:25:16 -0000\r\nDate: Wed, 14 Sep 2005 05:25:15 -0000\r\nTo: cantera@yahoogroups.com\r\nMessage-ID: &lt;dg8c7r+1gt1@...&gt;\r\nIn-Reply-To: &lt;945664f505090322073c7a9ec6@...&gt;\r\nUser-Agent: eGroups-EW/0.82\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=ISO-8859-1\r\nContent-Length: 3351\r\nX-Mailer: Yahoo Groups Message Poster\r\nX-Yahoo-Newman-Property: groups-system\r\nX-eGroups-Msg-Info: 1:12:0:0\r\nFrom: &quot;cassandralguy&quot; &lt;jcdoll@...&gt;\r\nSubject: Re: 1.6.0 on Mac OS X 10.4\r\nX-Yahoo-Group-Post: member; u=236082574; y=zO3JqJFBk6bUU3r7_RJjdxTz4mHC83ZAAXtIJD6JBNdg1ebladOoag\r\nX-Yahoo-Profile: cassandralguy\r\nX-eGroups-Approved-By: dggoodwin &lt;dgoodwin@...&gt; via web; 15 Sep 2005 16:43:51 -0000\r\n\r\nI fixed the problem. In python I ran the following commands:\n\nimport sys\nprint sys.path\n\nwhich indicated that /Applications/Cantera/bin and /Library/Python/2.3/ (another place \nthat files are installed by the binary installer) were not being searched for modules by \npython.\n\nIn order to fix it I modified /Library/Python/2.3/site-packages/Extras.pth by adding:\n\n/Library/Python/2.3/\n/Applications/Cantera/bin/\n\nRunning scripts from python doesn&#39;t work (can&#39;t find Cantera.oneD) but everything works \nperfectly from Matlab. Works for me!\n\nJoey Doll\nUC Berkeley\n\n--- In cantera@yahoogroups.com, Joey Doll &lt;jcdoll@g...&gt; wrote:\n&gt; Hello everybody. I just started using Cantera, or at least am trying\n&gt; to start using it. I&#39;m running Mac OS X 10.4.2 with the latest\n&gt; developer tools installed and Matlab 7 (R14). I installed Cantera\n&gt; using the 1.6.0 binary release however I am running into a few\n&gt; problems.\n&gt; \n&gt; When I try run_examples in Matlab I get the following error:\n&gt; \n&gt; &gt;&gt; run_examples\n&gt;   EQUIL  a chemical equilibrium example.\n&gt; \n&gt;      This example computes the adiabatic flame temperature and\n&gt;      equilibrium composition for a methane/air mixture as a function of\n&gt;      equivalence ratio.\n&gt; \n&gt; \n&gt; \n&gt; Traceback (most recent call last):\n&gt;   File &quot;./.cttmp1125719147.pyw&quot;, line 1, in ?\n&gt;     from ctml_writer import *\n&gt; ImportError: No module named ctml_writer\n&gt; ???\n&gt; \n&gt; ************************************************\n&gt;                 Cantera Error!\n&gt; ************************************************\n&gt; \n&gt; \n&gt; Procedure: ct2ctml\n&gt; Error:   could not convert input file to CTML.\n&gt;  Command line was:\n&gt; sleep 1; python ./.cttmp1125719147.pyw &&gt; ct2ctml.log\n&gt; \n&gt; Error in ==&gt; XML_Node.XML_Node at 11\n&gt;    x.id = ctmethods(10,15,0,src); % newxml(name)\n&gt; \n&gt; Error in ==&gt; Solution.Solution at 30\n&gt; doc = XML_Node(&#39;doc&#39;,src);\n&gt; \n&gt; Error in ==&gt; IdealGasMix at 39\n&gt;        s = Solution(a);\n&gt; \n&gt; Error in ==&gt; equil at 12\n&gt;    gas = IdealGasMix(&#39;gri30.cti&#39;);\n&gt; \n&gt; Error in ==&gt; run_examples at 3\n&gt; equil(0);\n&gt; \n&gt; And when I try to run the python examples directly from the command\n&gt; line I get the following error:\n&gt; \n&gt; -----:/Applications/Cantera/demos/python/flames -----$ python flame1.py\n&gt; Traceback (most recent call last):\n&gt;   File &quot;flame1.py&quot;, line 7, in ?\n&gt;     from Cantera import *\n&gt; ImportError: No module named Cantera\n&gt; -----:/Applications/Cantera/demos/python/flames -----$ python stflame1.py\n&gt; Traceback (most recent call last):\n&gt;   File &quot;stflame1.py&quot;, line 19, in ?\n&gt;     from Cantera import *\n&gt; ImportError: No module named Cantera\n&gt; \n&gt; My setup_cantera file looks like this (it was not modified after installation):\n&gt; \n&gt; #!/bin/sh\n&gt; LD_LIBRARY_PATH=/Applications/Cantera/lib/1.6.0:$LD_LIBRARY_PATH\n&gt; export LD_LIBRARY_PATH\n&gt; PATH=/Applications/Cantera/bin:$PATH\n&gt; export PATH\n&gt; PYTHON_CMD=python\n&gt; export PYTHON_CMD\n&gt; \n&gt; I&#39;ve also tried changing the python path to the actual binary but that\n&gt; didn&#39;t help things.\n&gt; \n&gt; It looks like Python doen&#39;t know that Cantera exists. I&#39;m just running\n&gt; python 2.3.0 which comes with 10.4 and have not tried installing 2.4.1\n&gt; fresh yet. Before I try doing so or build 1.6.0 I would just like to\n&gt; see if anybody has any success with a similar configuration and has\n&gt; any tips. I haven&#39;t found any documentation on installing Cantera on\n&gt; the Mac, am I missing something?\n&gt; \n&gt; Thanks!\n&gt; Joey\n\n\n\n\n\n"}}